eureka:
 client:
  register-with-eureka : true
  fetch-registry : true
  instance:
    hostname: localhost
service-url:
  default-zone: http://localhost:8761/eureka/
  
 microservice:
 payment-services:
  endpoints:
    endpoint:
     uri:http://PAYMENT-SERVICE/payment/processPayment
 order-services:
  endpoints:
    endpoint:
     uri:http://ORDER-SERVICE/orders/bookOrder
